### ISSUE TITLE
packing up new version for homebrew formula

### ISSUE THREAD

**Issue by cjwilburn** [ocochard/graphpath#4]
Hello!

Thanks for making such a great tool. I've made a [homebrew formula](https://github.com/cjwilburn/brew-graphpath) around it, but I'm seeing an error when building, because it appears that the v1.0 release is two commits behind current `HEAD`. I can add some handling to work around this, but I figured I would ask if it was all right for me to create a v1.1.0 release for these commits before I write the work-around in the homebrew formula.

Thanks!

**Comment by ocochard** [comment]
Hi, I've tagged the 1.1 release. Is this okay for you ?

**Comment by cjwilburn** [comment]
I think that will work. Thanks!
